# Use official Python slim image
FROM python:3.11-slim

# Set workdir inside container
WORKDIR /app

# Copy requirements and install
COPY . .
RUN pip install --no-cache-dir -r requirements.txt



# Expose port FastAPI runs on
EXPOSE 8000

# Run the FastAPI app with uvicorn
CMD ["uvicorn", "api_app:app", "--host", "0.0.0.0", "--port", "8000"]
